spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: registry-service

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

gateway_url: ${API_GATEWAY_URL:http://localhost:8040}